name: bart-tasks
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - numpy
  - pandas
  - pip
  - tqdm
  - pytest
  - wandb
  - pip:
    - "git+https://github.com/SKT-AI/KoBART#egg=kobart"
